version: '3.9'

services:

  mongodb:
    container_name: mongodb
    image: mongo:6.0.4
    volumes:
      - $APPDATA/mongodb:/data/db
    environment:
      - TZ=$TZ
    restart: "unless-stopped"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - $APPDATA/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - TZ=$TZ
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: "unless-stopped"

  graylog:
    container_name: graylog
    image: graylog/graylog:5.0.2
    volumes:
      - $APPDATA/graylog:/usr/share/graylog/data
    environment:
      - TZ=$TZ
      - ROOT_TIMEZONE=$TZ
      - GRAYLOG_TIMEZONE=$TZ
      # CHANGE ME (must be at least 16 characters)! 
      # This is not your password, this is meant for salting the password below.
      - GRAYLOG_PASSWORD_SECRET=$GRAYLOG_SECRET
      # Username is "admin"
      # Password is "admin", change this to your own hashed password. 
      #   'echo -n "password" | sha256sum' 
      - GRAYLOG_ROOT_PASSWORD_SHA2=$GRAYLOG_ROOT_PW_SHA2
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog UDP
      - 1514:1514/udp
      # Syslog TCP
      - 1514:1514
    restart: "unless-stopped"

  influxdb:
    container_name: influxdb
    image: influxdb:2.6.1
    ports:
      - '8086:8086'
    volumes:
      - $APPDATA/influxdb2:/var/lib/influxdb2
    environment:
      - TZ=$TZ
    restart: "unless-stopped"

  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.10
    ports:
      - '3000:3000'
    volumes:
      - $APPDATA/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - TZ=$TZ
      - GF_SECURITY_ADMIN_USER=$GF_SECURITY_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GF_SECURITY_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=$GF_INSTALL_PLUGINS
    restart: "unless-stopped"
